# Generated by Django 5.1.15 on 2026-04-16 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_menuoption'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menus.menuoption'),
        ),
        migrations.AddField(
            model_name='order',
            name='option_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
