# Generated by Django 5.1.15 on 2026-04-11 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('amount_cop', models.IntegerField(default=299000)),
                ('starts_at', models.DateField()),
                ('expires_at', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Activa'), ('expiring_soon', 'Por vencer'), ('expired', 'Vencida'), ('suspended', 'Suspendida')], default='active', max_length=20)),
                ('bold_payment_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saas_subscription', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Suscripción SaaS',
                'verbose_name_plural': 'Suscripciones SaaS',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cop', models.IntegerField()),
                ('paid_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.saassubscription')),
            ],
            options={
                'verbose_name': 'Pago registrado',
                'verbose_name_plural': 'Pagos registrados',
                'ordering': ['-paid_at'],
            },
        ),
    ]
