# Generated by Django 5.1.15 on 2026-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuingredient',
            name='grams',
            field=models.IntegerField(blank=True, help_text='Cantidad en gramos (opcional)', null=True),
        ),
    ]
