# Generated by Django 5.1.15 on 2026-04-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menuingredient_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
