# Generated by Django 5.1.15 on 2026-04-16 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_make_valid_until_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menus.dailymenu')),
            ],
            options={
                'verbose_name': 'Opción de precio',
                'verbose_name_plural': 'Opciones de precio',
                'ordering': ['order', 'id'],
            },
        ),
    ]
